output:ComplexInteger.o Assign2_Prob1.o
	g++ Assign2_Prob1.cpp -o output


ComplextInteger.o:ComplexInteger.cpp
	g++ -c ComplexInteger.cpp

Assign2_Prob1.o:Assign2_Prob1.cpp
	g++ -c Assign2_Prob1.cpp



clean:
	rm*.output