output:Matrix.o Assign2_Prob2.o
	g++ Assign2_Prob2.cpp -o output


Matrix.o:Matrix.cpp
	g++ -c Matrix.cpp

Assign2_Prob2.o:Assign2_Prob2.cpp
	g++ -c Assign2_Prob2.cpp



clean:
	rm*.output