output:LinkedList.o Assign2_Prob4.o
	g++ Assign2_Prob4.cpp -o output


LinkedList.o:LinkedList.cpp
	g++ -c LinkedList.cpp

Assign2_Prob4.o:Assign2_Prob4.cpp
	g++ -c Assign2_Prob4.cpp



clean:
	rm*.output