output:String.o Assign2_Prob3.o
	g++ Assign2_Prob3.cpp -o output


String.o:String.cpp
	g++ -c String.cpp

Assign1_Prob3.o:Assign2_Prob3.cpp
	g++ -c Assign2_Prob3.cpp


clean:
	rm*.o output